name: Java CI with Maven

on:
  # Triggers on push or pull request to main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows manual run
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up Java Development Kit
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # distribution of OpenJDK
          cache: 'maven' # Cache Maven dependencies

      # Runs Maven test
      - name: Run unit tests with Maven
        working-directory: ./maven-archetype-quickstart
        run: mvn --batch-mode test # --batch-mode runs Maven in non-interactive mode

      # Test report
      - name: Report
        uses: dorny/test-reporter@v1
        if: always() # Ensures this step runs even if previous steps (like tests) fail
        with:
          name: Maven Tests # Name of the check run that will be created
          path: target/surefire-reports/*.xml # Path to the JUnit XML reports
          reporter: java-junit # Reporter to use (specific to the format of your test results)
          fail-on-error: 'true' # Fails the workflow step if test failures are found in the report
