name: Java CI with Maven

on:
  # Triggers on push or pull request to main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows manual run
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write   # For dorny/test-reporter to create check runs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up Java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # distribution of OpenJDK
          cache: 'maven' # Cache Maven dependencies

      # Runs Maven test
      - name: Run unit tests with Maven
        working-directory: ./maven-archetype-quickstart
        run: mvn --batch-mode -X test # --batch-mode runs Maven in non-interactive mode
      
      # Upload TestNG HTML reports
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./maven-archetype-quickstart/target/surefire-reports
          retention-days: 1
      
      # # html test report for junit (TestNG does this w/o an external library)
      # - name: Publish Test Report # Show tests in UI (adds html link)
      #   uses: dorny/test-reporter@v1
      #   if: always() # Run even if previous tests fail
      #   with:
      #     name: Maven TestNG Tests
      #     path: maven-archetype-quickstart/target/surefire-reports/*.xml
      #     reporter: java-junit
      #     fail-on-error: 'true'

