name: Java CI with Maven

on:
  # Triggers on push or pull request to main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows manual run
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up Java Development Kit
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # distribution of OpenJDK
          cache: 'maven' # Cache Maven dependencies

      # Runs Maven test
      - name: Run unit tests with Maven
        working-directory: ./maven-archetype-quickstart
        run: mvn --batch-mode test # --batch-mode runs Maven in non-interactive mode

      # Test report
      - name: Publish Test Report # Show tests in UI
        uses: dorny/test-reporter@v1
        if: always() # Run even if previous tests fail
        with:
          name: Maven JUnit Tests
          path: maven-archetype-quickstart/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: 'true' # Fails the workflow if tests failed
