name: Java CI with Maven and TestNG

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run unit tests with Maven
        working-directory: ./maven-archetype-quickstart
        run: mvn --batch-mode test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: ./maven-archetype-quickstart/target/surefire-reports/*.xml

      # - name: Publish Test Results Summary (dorny/test-reporter) for junit
      #   uses: dorny/test-reporter@v1
      #   if: always()
      #   with:
      #     name: Maven Test Results
      #     path: ./maven-archetype-quickstart/target/surefire-reports/*.xml
      #     reporter: java-junit
      #     fail-on-error: 'true'

      # - name: Upload TestNG HTML Report Artifact
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: testng-html-report
      #     path: ./maven-archetype-quickstart/test-output/
      #     retention-days: 1
